### ISSUE TITLE
How to update the default size using this ansible role?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-postfix#2]
```
user@localhost:~# telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 fqdn ESMTP Postfix (Ubuntu)

ehlo hello

250-fqdn
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```

**Comment by 030** [comment]
```
postconf -e "message_size_limit = 15728640"
```

and restarting postfix

```
systemctl restart postfix
```

telnet localhost 25

15728640

**Comment by geerlingguy** [comment]
This role is meant to be extremely simple and just get postfix running on the server with all the defaults. If you have any simple additions you can propose to make the role change settings on the fly, I may consider adding them; otherwise, the defaults are often adequate, and playbooks using this role can customize things further (e.g. with a `command: postconf -e "message_size_limit = 15728640"` and a `when` conditional on it after this role runs in the playbook).
